version: '3.1'

services:
  oracle-express:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-express
    volumes:      
      - ./oracle-express:/opt/oracle/oradata    
    ports:
      - 1521:1521
      # - 5500:5500
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_DATABASE=oracle-express

  